import catchAsync from '../utils/catchAsync.js'
import AppError from '../utils/appError.js'

const chatAI = catchAsync(async (req, res, next) => {})

const chatBot = catchAsync(async (req, res, next) => {})

export default { chatAI, chatBot }
